### ISSUE TITLE
баг в туторе

### ISSUE THREAD

**Issue by 221V** [pevzi/beep#1]
https://kolenka.net/posts/vvedenie-v-lua-chast-2-tabliczy
часть 1 -- есть, часть 3 -- есть,
часть 2 -- сразу комменты идут...
где статья?)

**Comment by 221V** [comment]
https://kolenka.net/posts/vvedenie-v-lua-chast-3-upravlyayushhie-instrukczii
а тут какие-то битые смайлики-картинки в коде..

**Comment by pevzi** [comment]
Спасибо, но вообще-то это не имеет отношения к игре beep. У туториала есть [свой репозиторий](https://github.com/pevzi/lua-intro), где лежит чуть более актуальная версия, чем та, что сейчас на Коленке.

В планах было сначала довести всё до ума, дописать часть про модули, и уже потом опубликовать готовый вариант на Коленку, но дело немного затянулось 😕

> где статья?)
> а тут какие-то битые смайлики-картинки в коде..

Это Коленка переехала на новый самописный движок, и походу есть некоторые нюансы (баги) в работе механизма, который отрисовывает содержимое постов:

- Последовательности вида `:foo:` он пытается преобразовать в смайлики на лету даже внутри тегов с кодом.
- Статья про таблицы сломалась из-за того, что сайт прогоняет тексты постов через шаблонизатор Vue (возможно, для фильтрации всяких опасных тегов?), а двойные фигурные скобки в строке `matrix = {{1, 2, 3}, {4, 5, 6}, {7, 8, 9}}` совпадают с синтаксисом интерполяции строк в шаблонах Vue.

По-хорошему, об этом нужно написать в багтрекер [самого сайта](https://github.com/NaKolenke/kolenka-frontend).
